title: Blog
author: Christopher Beitel, Ph.D.
email: cb@marrow.io
description: >
  Building infrastructure for machine learning applications in
  biology with a special interest in the biomedical sciences and predictive
  wellness. Ph.D. in Genetics

twitter_username: cwbeitel
github_username:  cwbeitel

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
